export const API_ENDPOINTS = {
  USERS: {
    BASE: '/users',
    BY_ID: (id: number) => `/users/${id}`,
    DEACTIVATE: (id: number) => `/users/${id}/deactivate`,
    REACTIVATE: (id: number) => `/users/${id}/reactivate`,
  },
  NOTIFICATIONS: {
    BASE: '/notifications',
    UNREAD_COUNT: '/notifications/unread-count',
    MARK_READ: (id: number) => `/notifications/${id}/read`,
    MARK_ALL_READ: '/notifications/read-all',
    DELETE: (id: number) => `/notifications/${id}`,
  },
  AUDIT_LOGS: {
    BASE: '/audit-logs',
  },
  SUBJECTS: {
    BASE: '/subjects',
    BY_ID: (id: number) => `/subjects/${id}`,
  },
  SUBJECT_OFFERINGS: {
    BASE: '/subject-offerings',
    BY_ID: (id: number) => `/subject-offerings/${id}`,
    INTERNAL_MARKS: (id: number) => `/subject-offerings/${id}/internal-marks`,
  },
  ASSESSMENTS: {
    BASE: '/assessments',
    BY_ID: (id: number) => `/assessments/${id}`,
    GRADES: (id: number) => `/assessments/${id}/grades`,
    SUMMARY: (id: number) => `/assessments/${id}/summary`,
    FINALIZE: (id: number) => `/assessments/${id}/finalize`,
  },
  GRADES: {
    ME: '/grades/me',
  },
  INTERNAL_MARKS: {
    ME: '/internal-marks/me',
  },
  ACADEMIC: {
    BATCHES: '/batches',
    SECTIONS: '/sections',
  },
  DASHBOARD: {
    SUMMARY: '/dashboard/summary',
  },
  PORTFOLIO: {
    ENTRIES: '/portfolio/entries',
    ENTRY: (id: number) => `/portfolio/entries/${id}`,
    SUBMIT: (id: number) => `/portfolio/entries/${id}/submit`,
    VERIFY: (id: number) => `/portfolio/entries/${id}/verify`,
    REJECT: (id: number) => `/portfolio/entries/${id}/reject`,
    ME: '/portfolio/me',
    ME_SUMMARY: '/portfolio/me/summary',
    REVIEW: '/portfolio/review',
    STUDENT: (studentId: number) => `/portfolio/students/${studentId}`,
    SUMMARY: '/portfolio/summary',
  },
  ENROLLMENTS: {
    BASE: '/course-enrollments',
    ME: '/course-enrollments/me',
    ROSTER: (offeringId: number) => `/course-enrollments/subject-offerings/${offeringId}`,
    ENROLL_SECTION: (offeringId: number) => `/course-enrollments/subject-offerings/${offeringId}/enroll-section`,
    STATUS: (id: number) => `/course-enrollments/${id}/status`,
  },
  TIMETABLE: {
    BASE: '/timetable',
    ME: '/timetable/me',
    BY_ID: (id: number) => `/timetable/${id}`,
  },
  ATTENDANCE: {
    SESSIONS: '/attendance/sessions',
    SESSION: (id: number) => `/attendance/sessions/${id}`,
    RECORDS: (id: number) => `/attendance/sessions/${id}/records`,
    FINALIZE: (id: number) => `/attendance/sessions/${id}/finalize`,
    CLASS_SUMMARY: (offeringId: number) => `/attendance/subject-offerings/${offeringId}/summary`,
    ME: '/attendance/me',
  },
  LESSON_PLANS: {
    BASE: '/lesson-plans',
    ME: '/lesson-plans/me',
    BY_ID: (id: number) => `/lesson-plans/${id}`,
    PROGRESS: (offeringId: number) => `/lesson-plans/subject-offerings/${offeringId}/progress`,
    COMPLETE: (id: number) => `/lesson-plans/${id}/complete`,
    CANCEL: (id: number) => `/lesson-plans/${id}/cancel`,
    REOPEN: (id: number) => `/lesson-plans/${id}/reopen`,
  },
  FEES: {
    ME: '/fees/me',
    STRUCTURES: '/fees/structures',
    STRUCTURE: (id: number) => `/fees/structures/${id}`,
    ASSIGN: (id: number) => `/fees/structures/${id}/assign`,
    ACCOUNTS: '/fees/accounts',
    ACCOUNT: (id: number) => `/fees/accounts/${id}`,
    PAYMENTS: (accountId: number) => `/fees/accounts/${accountId}/payments`,
    WAIVE: (accountId: number) => `/fees/accounts/${accountId}/waive`,
    SUMMARY: '/fees/summary',
  },
  RECEIPTS: {
    BASE: '/receipts',
    ME: '/receipts/me',
    BY_ID: (id: number) => `/receipts/${id}`,
  },
  EXAM_PERIODS: {
    BASE: '/exam-periods',
    BY_ID: (id: number) => `/exam-periods/${id}`,
    OPEN: (id: number) => `/exam-periods/${id}/open`,
    CLOSE: (id: number) => `/exam-periods/${id}/close`,
  },
  EXAM_REGISTRATIONS: {
    BASE: '/exam-registrations',
    ME: '/exam-registrations/me',
    BY_ID: (id: number) => `/exam-registrations/${id}`,
    OPEN_PERIODS: '/exam-registrations/periods',
    ELIGIBLE: (periodId: number) => `/exam-registrations/periods/${periodId}/eligible-subjects`,
    SAVE_MINE: (periodId: number) => `/exam-registrations/periods/${periodId}/me`,
    SUBMIT_MINE: (periodId: number) => `/exam-registrations/periods/${periodId}/me/submit`,
    APPROVE: (id: number) => `/exam-registrations/${id}/approve`,
    REJECT: (id: number) => `/exam-registrations/${id}/reject`,
  },
  RESULTS: {
    BASE: '/results',
    ME: '/results/me',
    SHEET: (offeringId: number, periodId: number) => `/results/subject-offerings/${offeringId}/periods/${periodId}`,
    PUBLISH: (offeringId: number, periodId: number) => `/results/subject-offerings/${offeringId}/periods/${periodId}/publish`,
  },
  FEEDBACK: {
    FORMS: '/feedback/forms',
    MY_FORMS: '/feedback/forms/me',
    FORM: (id: number) => `/feedback/forms/${id}`,
    OPEN: (id: number) => `/feedback/forms/${id}/open`,
    CLOSE: (id: number) => `/feedback/forms/${id}/close`,
    ANALYTICS: (id: number) => `/feedback/forms/${id}/analytics`,
    RESPONSES: (id: number) => `/feedback/forms/${id}/responses`,
    SUBMIT: (id: number) => `/feedback/forms/${id}/submit`,
  },
  LEETCODE: {
    FILTERS: '/leetcode/filters',
    STATS: '/leetcode/stats',
    ME: '/leetcode/me',
    ME_STATS: '/leetcode/me/stats',
    PROFILE_URLS: '/leetcode/profile-urls',
    TOP: '/leetcode/top',
  },
} as const;
