export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  COURSE_ENROLLMENT: '/dashboard/course-enrollment',
  TIMETABLE: '/dashboard/timetable',
  ATTENDANCE: '/dashboard/attendance',
  ATTENDANCE_SESSION: (id: number) => `/dashboard/attendance/sessions/${id}`,
  LESSON_PLAN: '/dashboard/lesson-plan',
  FEES: '/dashboard/fees',
  RECEIPTS: '/dashboard/receipts',
  EXAM_REGISTRATION: '/dashboard/exam-registration',
  RESULTS: '/dashboard/results',
  FEEDBACK: '/dashboard/feedback',
  NOTIFICATIONS: '/dashboard/notifications',
  AUDIT_LOG: '/dashboard/audit-log',
  USERS: '/dashboard/users',
  SUBJECTS: '/dashboard/subjects',
  SUBJECT_OFFERINGS: '/dashboard/subject-offerings',
  ASSESSMENTS: '/dashboard/assessments',
  INTERNAL_MARKS: '/dashboard/internal-marks',
  MY_GRADES: '/dashboard/my-grades',
  LEETCODE: '/dashboard/leetcode',
  PORTFOLIO: '/dashboard/portfolio',
  PORTFOLIO_REVIEW: '/dashboard/portfolio/review',
  PORTFOLIO_ANALYTICS: '/dashboard/portfolio/analytics',
  PORTFOLIO_STUDENT: (studentId: number) => `/dashboard/portfolio/students/${studentId}`,
} as const;
